# Generated by Django 4.2.7 on 2023-12-23 07:51

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0004_rename_profile_picture_account_profile_picture'),
        ('seller_Home_app', '0003_product_product_wishlist'),
        ('Home_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('Product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller_Home_app.product')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Account.account')),
            ],
        ),
        migrations.DeleteModel(
            name='Edit_menu',
        ),
    ]
