# Generated by Django 4.2.7 on 2023-12-05 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('Name', models.CharField(max_length=25)),
                ('Mobile', models.PositiveBigIntegerField()),
                ('Email', models.EmailField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('Address', models.TextField(max_length=150)),
                ('Password', models.CharField(max_length=30)),
                ('user', models.CharField(choices=[('Buyer', 'Buyer'), ('Seller', 'Seller')], max_length=15)),
            ],
        ),
    ]
