# Generated by Django 4.2.7 on 2023-12-12 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0002_remove_account_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='profile_picture',
            field=models.ImageField(default='', upload_to='Profile_picture/'),
        ),
    ]
