# Generated by Django 4.2.7 on 2023-12-14 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0003_account_profile_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='profile_picture',
            new_name='Profile_picture',
        ),
    ]
