# Generated by Django 4.2.7 on 2023-12-23 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller_Home_app', '0002_rename_product_name_product_product_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_wishlist',
            field=models.BooleanField(default=False),
        ),
    ]
