# Generated by Django 4.2.7 on 2023-12-23 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller_Home_app', '0003_product_product_wishlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_wishlist',
        ),
    ]
