# Generated by Django 4.2.7 on 2023-12-23 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller_Home_app', '0004_remove_product_product_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_wishlist',
            field=models.BooleanField(default=False),
        ),
    ]
