# Generated by Django 4.2.7 on 2023-12-23 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller_Home_app', '0005_product_product_wishlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_wishlist',
            new_name='Iswishlist',
        ),
    ]
