# Generated by Django 4.2.7 on 2023-12-23 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller_Home_app', '0006_rename_product_wishlist_product_iswishlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Product_description',
            field=models.TextField(max_length=250),
        ),
        migrations.AlterField(
            model_name='product',
            name='Product_name',
            field=models.CharField(max_length=50),
        ),
    ]
