# Generated by Django 4.2.7 on 2023-12-24 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller_Home_app', '0008_alter_product_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Iscart',
            field=models.BooleanField(default=False),
        ),
    ]
