# Generated by Django 4.2.7 on 2023-12-14 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller_Home_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Product_Name',
            new_name='Product_name',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Product_Price',
            new_name='Product_price',
        ),
    ]
